### PR TITLE
Add Maxime Biollaz

### PR DESCRIPTION
**Pull request by HiMeteor**

### CODE REVIEW

**Comment by mardaisado** [comment]
image

**Comment by 73jn** [comment]
99-pull-request

**Comment by sieri** [comment]
image

**Comment by metc** [comment]
Thanks for your contribution.
Please rebase (`git rebase`) your work on top of the latest `master` branch so I can merge your work. Thank you.

**Review by metc — CHANGES_REQUESTED** [review]
Thanks for your contribution.
Please rebase (`git rebase`) your work on top of the latest `master` branch so I can merge your work. Thank you.

**Review by metc — APPROVED** [review]

**Pull request merged**
